### ISSUE TITLE
Support animation between points with x1 and y1 channels.

### ISSUE THREAD

**Issue by bmschmidt** [CreatingData/deepscatter#21]
I've from time to time supported x1 and y1 aesthetic channels that allow animations to interpolate between two points. This can be nice for showing, e.g., flow of migrants between countries; flow of dollars between donors.

Most of the pieces are there to restore it.

**Comment by bmschmidt** [comment]
Complete

**Comment by davidnmora** [comment]
@bmschmidt I'm not sure I understand what this is useful for. When I update `x` or `y` to a new field, interpolation already happens, without needing `x0` or `y0`. Maybe I'm missing the use case? 😅
