### ISSUE TITLE
Invalid NPM package.json

### ISSUE THREAD

**Issue by YousefED** [CreatingData/deepscatter#45]
Exciting work!

I was trying to load this module via ESM, but there seems to be some corrupt links in package.json:

https://unpkg.com/browse/deepscatter@2.4.0/package.json lists "./dist/deepscatter.es.js" as module.

However, the "dist" directory only contains "deepscatter.js". See https://unpkg.com/browse/deepscatter@2.4.0/dist/

**Comment by bmschmidt** [comment]
Thanks for the report! I just changed the link in `package.json` to reflect the new location and bumped the version on npm--hopefully that fixes it. Please reopen if not.
